# Generated by Django 3.2.8 on 2021-10-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='disable_at',
            new_name='disabled_at',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='enable_at',
            new_name='enabled_at',
        ),
    ]
