# Generated by Django 3.2.8 on 2021-10-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20211012_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(choices=[('Enabled', 'Enable'), ('Disabled', 'Disable')], default='Disabled', max_length=8),
        ),
    ]
